### ISSUE TITLE
Tracciato custom

### ISSUE THREAD

**Issue by ziorick** [consiglionazionaledellericerche/epas-client#6]
E' possibile documentare come il software legge il file delle timbrature (nome da adottare) e come descrivere anche con regex il tracciato utilizzato?

**Comment by criluc** [comment]
Il formato del nome da adottare per i file delle timbrature da leggere non è predefinito, però con i parametri FTP_FILE_PREFIX ed FTP_FILE_SUFFIX si controlla i nomi dei file da processare, gli altri file non corrispondenti vengono scartati. Questo è già documentato nel README, ho aggiunto adesso nel README che quei due parametri si applicano alle modalità local/ftp/sftp.

La regex da scrivere per il proprio tracciato record è documentata nel README al parametro REGEX_STAMPING, adesso ho aggiunto quali sono i gruppi obbligatori da definire nella regex.

E' sufficiente o manca altro?

**Comment by criluc** [comment]
Chiuso per inattività.
